spring:
  application:
    name: zc-ai-agent
  profiles:
    active: local
server:
  #后端端口号
  port: 8123
  servlet:
    context-path: /api
# springdoc-openapi 接口文档配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.zc.zcaiagent.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
