spring:
  application:
    name: zc-ai-agent
  profiles:
    active: local

  data:
    redis:
      host: 192.168.177.130
      port: 6379
      password: Zc.123456
      database: 0
      timeout: 5000
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
server:
  #后端端口号
  port: 8123
  servlet:
    context-path: /api
# springdoc-openapi 接口文档配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.zc.zcaiagent.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn

