logging:
  level:
    org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor: debug

spring:
  application:
    name: zc-ai-agent
  profiles:
    active: local

  data:
    redis:
      host: 192.168.177.130
      port: 6379
      password: Zc.123456
      database: 0
      timeout: 5000
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
#ollama大模型导入的
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: deepseek-r1:1.5b
    vectorstore:
      pgvector:
        index-type: HNSW
        dimensions: 1536 #向量维度(后面不可以跟改，要确定好)
        distance-type: COSINE_DISTANCE #向量距离类型
        max-document-batch-size: 10000 #向量批量处理大小

  datasource:
    url: jdbc:postgresql://rm-cn-rno4ayst20001hho.rwlb.rds.aliyuncs.com:5432/yu_ai_agent
    username: my_user






server:
  #后端端口号
  port: 8123
  servlet:
    context-path: /api
# springdoc-openapi 接口文档配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.zc.zcaiagent.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn

